[package]
name = "manager"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tokio-util = { workspace = true }
futures-util = "0.3"
interprocess = { workspace = true }
protocol = { path = "../protocol" }
serde = { workspace = true }
serde_json = { workspace = true }
colored = "3.1"
tabled = { version = "0.22.0", features = ["ansi"]}