[workspace]
members = [
    "manager",
    "cli",
    "protocol",
]

[workspace.dependencies]
tokio = {version = "1.53.1", features=["process", "io-std", "macros", "rt"]}
tokio-util = {version = "0.7.19", features=["full"]}
interprocess = { version = "2.4.4", features = ["tokio"] }
serde = { version = "1.0.229", features = ["derive"]}
protocol = { path = "./protocol/" }